#!/bin/bash

platform='unknown'
unamestr=`uname`
if [[ "$unamestr" == 'Linux' ]]; then
   platform='linux'
elif [[ "$unamestr" == 'FreeBSD' ]]; then
   platform='freebsd'
 elif [[ "$unamestr" == 'Darwin' ]]; then
    platform='osx'
fi

if [[ $platform != 'osx' ]]; then
  alias docker='sudo docker'
fi

docker run -d --link namenode:namenode --workdir /usr/local/hadoop yarn-cluster /etc/bootstrap.sh -d -datanode
